In [2]:
# import package
import numpy as np

In [4]:
# dir(np)

In [5]:
list_ = [1,2,3]
arr = np.array(list_)
print(arr)
print(type(arr))

[1 2 3]
<class 'numpy.ndarray'>


In [6]:
type(list_[0])

int

In [7]:
type(arr[0])

numpy.int64

In [8]:
list_ = [1,2,3,'bangalore']
arr = np.array(list_)
print(arr)
print(type(arr))

['1' '2' '3' 'bangalore']
<class 'numpy.ndarray'>


In [9]:
type(arr[0])

numpy.str_

In [10]:
l_ = list(range(1,10))

In [11]:
l_

[1, 2, 3, 4, 5, 6, 7, 8, 9]

In [12]:
l_*2 # broadcasting not supported

[1, 2, 3, 4, 5, 6, 7, 8, 9, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [13]:
# multiply each element by 2
arr = np.array(l_)
arr*2 # broadcasting supported

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

## creating arrays

In [16]:
## 
arr = np.empty(shape = 5)
arr

array([4.e-323, 0.e+000, 0.e+000, 0.e+000, 0.e+000])

In [18]:
arr = np.empty(shape = (2,3), dtype = int)
arr

array([[0, 0, 0],
       [0, 0, 0]])

In [19]:
## 
arr = np.ones(shape = 5)
arr

array([1., 1., 1., 1., 1.])

In [20]:
arr = np.ones(shape = (3,5))
arr

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [22]:
##
arr = np.zeros(shape = 5)
arr

array([0., 0., 0., 0., 0.])

In [23]:
##
arr = np.zeros(shape = (3,4,5))
arr

array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]])

In [28]:
##
arr = np.linspace(1,20,10)
arr

array([ 1.        ,  3.11111111,  5.22222222,  7.33333333,  9.44444444,
       11.55555556, 13.66666667, 15.77777778, 17.88888889, 20.        ])

In [33]:
##
arr = np.arange(1,10,2, dtype= float)
arr

array([1., 3., 5., 7., 9.])

In [35]:
##
arr = np.random.rand(5)
arr

array([0.73938415, 0.51132219, 0.2699267 , 0.8674532 , 0.59491119])

In [45]:
arr = np.random.rand(2,3)
arr

array([[0.8643424 , 0.09821652, 0.29574032],
       [0.03811403, 0.69218164, 0.23255197]])

In [38]:
arr = np.random.randn(5)
arr

array([-0.87357245,  0.90057153, -0.24617932, -0.2850656 , -0.62577825])

In [39]:
arr = np.random.randn(5,2)
arr

array([[-0.37020745,  0.15758629],
       [ 1.51078305,  0.79334893],
       [-0.1832048 ,  1.70444245],
       [ 0.00755552, -0.11758092],
       [ 0.0334769 ,  1.34650651]])

In [43]:
arr = np.random.randint(2,7)
arr

2

In [46]:
###
# np.mean(), min, np.min(), np.std(),np.max()

In [47]:
##
arr = np.random.randn(5,2) # 5 rows and 2 columns
arr

array([[-0.42329445,  0.21752308],
       [ 0.68013284, -0.61997613],
       [-0.14308307,  0.02197   ],
       [-0.45899067,  0.90431061],
       [-1.47186135, -0.14725633]])

In [50]:
arr[2][1] # 3rd row and 2nd column # 2nd index and 1st index

0.021969997196211392

In [51]:
arr[2,1] ## 

0.021969997196211392

In [52]:
### a[i][j] = a[i,j] both are valid for array object

In [55]:
##
arr = np.array([1,2,3,4])
print(arr)
n_arr  = arr.reshape((2,2))
print(n_arr)

[1 2 3 4]
[[1 2]
 [3 4]]


In [57]:
##
# arr = np.array([1,2,3,4])
# print(arr)
# n_arr  = arr.reshape((2,3))
# print(n_arr)

In [63]:
## impact of + operator 
arr1 = np.arange(1,11,1).reshape(2,5)
print(arr1)
arr2 = np.random.rand(2,5)
print(arr2)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
[[0.86047546 0.09978704 0.61607611 0.14997903 0.44543633]
 [0.5442157  0.31640788 0.11050315 0.73654052 0.96599264]]


In [64]:
arr1+arr2

array([[ 1.86047546,  2.09978704,  3.61607611,  4.14997903,  5.44543633],
       [ 6.5442157 ,  7.31640788,  8.11050315,  9.73654052, 10.96599264]])

In [65]:
# impact of * operator
arr1*arr2

array([[0.86047546, 0.19957407, 1.84822834, 0.59991611, 2.22718164],
       [3.26529418, 2.21485513, 0.8840252 , 6.62886471, 9.65992644]])

In [67]:
## matrix multiplication
arr1 = np.arange(1,11,1).reshape(2,5)
print(arr1)
arr2 = np.random.rand(5,2)
print(arr2)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
[[0.81908965 0.22841439]
 [0.86745867 0.42057786]
 [0.4841086  0.99328911]
 [0.1258565  0.85667417]
 [0.14963612 0.71010641]]


In [68]:
np.dot(arr1,arr2) # matrix muplication 

array([[ 5.2579394 , 11.02666615],
       [17.48868712, 27.0719758 ]])

## Pandas

In [70]:
## import package

import pandas as pd

In [72]:
s = pd.Series(data = [1,2,3])
print(type(s))

<class 'pandas.core.series.Series'>


In [73]:
s

0    1
1    2
2    3
dtype: int64

In [75]:
s = pd.Series(data = [1,2,3], index = ['a','b','c'])
print(type(s))
s

<class 'pandas.core.series.Series'>


a    1
b    2
c    3
dtype: int64

In [77]:
s = pd.Series(data = np.array(range(1,10)))
s

0    1
1    2
2    3
3    4
4    5
5    6
6    7
7    8
8    9
dtype: int64

In [78]:
s = pd.Series(data = ['1','2','3'])
s

0    1
1    2
2    3
dtype: object

In [82]:
s = pd.Series(data = [1,2,3.0,4], name = 'Float')
s

0    1.0
1    2.0
2    3.0
3    4.0
Name: Float, dtype: float64

In [83]:
s = pd.Series(data = {'a':'banglore','b':'chennai','c':'mumbai'})
s

a    banglore
b     chennai
c      mumbai
dtype: object

In [84]:
## Accessing elements

In [85]:
s = pd.Series(data =[1,2,3,4,7,8,12])
s

0     1
1     2
2     3
3     4
4     7
5     8
6    12
dtype: int64

In [86]:
##  accesing by index
s[3]

4

In [88]:
s[2:5]

2    3
3    4
4    7
dtype: int64

In [89]:
s = pd.Series(data =[1,2,3,4,7,8,12], 
              index = ['a','b','d','e','f','g','j'])
s

a     1
b     2
d     3
e     4
f     7
g     8
j    12
dtype: int64

In [90]:
## accessing by label
s['e']

4

In [93]:
## 
s = pd.Series(data = 5, index = np.arange(10))
s

0    5
1    5
2    5
3    5
4    5
5    5
6    5
7    5
8    5
9    5
dtype: int64

In [94]:
## dataframe

In [95]:
## 
pd.DataFrame()

Empty DataFrame
Columns: []
Index: []

In [96]:
### Dataframe from list
df = pd.DataFrame(data = np.arange(5))
print(type(df))

<class 'pandas.core.frame.DataFrame'>


In [97]:
df

0
0  0
1  1
2  2
3  3
4  4

In [98]:
df = pd.DataFrame(data = np.arange(50).reshape(2,25))
df

0   1   2   3   4   5   6   7   8   9   ...  15  16  17  18  19  20  21  \
0   0   1   2   3   4   5   6   7   8   9  ...  15  16  17  18  19  20  21   
1  25  26  27  28  29  30  31  32  33  34  ...  40  41  42  43  44  45  46   

   22  23  24  
0  22  23  24  
1  47  48  49  

[2 rows x 25 columns]

In [100]:
### Dataframe from list
df = pd.DataFrame(data = np.arange(5), columns=['c1'], 
                 index = ['a','d','r','g','a'])
df

c1
a   0
d   1
r   2
g   3
a   4

In [103]:
# ### Dataframe from list
# df = pd.DataFrame(data = np.arange(5).reshape(1,5), columns=['c1'], 
#                  index = ['a','d','r','g','a'])
# df

In [102]:
df = pd.DataFrame(data = np.arange(6).reshape(2,3),
                  columns=['c1','c2','c3'], 
                 index = ['a','d'])
df

c1  c2  c3
a   0   1   2
d   3   4   5

In [104]:
### nested list
df = pd.DataFrame(data = [[1,2,3],[4,5,6]],
                  columns =['c1','c2','c3'], 
                  index   = ['a','d'])
df

c1  c2  c3
a   1   2   3
d   4   5   6

In [105]:
### nested list
df = pd.DataFrame(data = [[1,2,3],[4,5]],
                  columns=['c1','c2','c3'], 
                  index = ['a','d'])
df

c1  c2   c3
a   1   2  3.0
d   4   5  NaN

In [107]:
### nested list
df = pd.DataFrame(data = [[1,2,3,4],[4,5]],
                  columns=['c1','c2','c3','c4'], 
                  index = ['a','d'])
df

c1  c2   c3   c4
a   1   2  3.0  4.0
d   4   5  NaN  NaN

In [108]:
### nested list
df = pd.DataFrame(data = [[1,2,'3',4],[4,5]],
                  columns=['c1','c2','c3','c4'], 
                  index = ['a','d'])
df

c1  c2    c3   c4
a   1   2     3  4.0
d   4   5  None  NaN

In [ ]:
# inf
# -inf

In [113]:
### nested list
df = pd.DataFrame(data = {'a':'bangalore','b':'chennai','c':'goa'},
                 index = ['a'])
df

a        b    c
a  bangalore  chennai  goa

In [115]:
### nested list
df = pd.DataFrame(data = {'a':[1,2,3],'b':[4,5,6]})
df

a  b
0  1  4
1  2  5
2  3  6

In [ ]:
##
# accessing 